//USER CONSTANTS
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const GET_ACTIVE_POLLS = 'GET_ACTIVE_POLLS';
export const GET_ACTIVE_POLLS_TITLES = "GET_ACTIVE_POLLS_TITLES";
export const DATA_FETCH_FAILURE = "DATA_FETCH_FAILURE";

export const CAST_VOTE_SUCCESS = "CAST_VOTE_SUCCESS";
export const CAST_VOTE_FAILURE = "CAST_VOTE_FAILURE";

export const VOTE_COUNT_SUCCESS = "VOTE_COUNT_SUCCESS"
export const VOTE_COUNT_FAILURE = "VOTE_COUNT_FAILURE"

export const CHECK_IS_ADMIN_SUCCESS = 'CHECK_IS_ADMIN_SUCCESS';
export const CHECK_IS_ADMIN_FAILURE = 'CHECK_IS_ADMIN_FAILURE';

export const ADD_POLLS_SUCCESS = 'ADD_POLLS_SUCCESS';
export const ADD_POLLS_FAILURE = 'ADD_POLLS_FAILURE';