//USER CONSTANTS
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const GET_ACTIVE_POLLS = 'GET_ACTIVE_POLLS';
export const GET_ACTIVE_POLLS_TITLES = "GET_ACTIVE_POLLS_TITLES";
export const DATA_FETCH_FAILURE = "DATA_FETCH_FAILURE";